import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@shared/lib/database/supabase/server';
import { awardPoints, updateUserStreak } from '@shared/services/gamification.service';
import { sendBookingConfirmationEmail } from '@shared/lib/email/resend';
import { getAffiliateUserIdForReferredUser } from '@shared/lib/utils/affiliate.server';

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      orderId,
      hospitalId,
      startDate,
      endDate,
      durationDays,
      packageType,
      packageName,
      unitPrice,
      totalPrice,
      notes,
      specialRequests,
    } = body;

    // Validate required fields
    if (
      !orderId ||
      !hospitalId ||
      !startDate ||
      !endDate ||
      !durationDays ||
      !packageType ||
      !packageName ||
      !unitPrice ||
      !totalPrice
    ) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Create hospital appointment (using unified appointments table)
    const { data: appointment, error: bookingError } = await supabase
      .from('appointments')
      .insert({
        order_id: orderId,
        user_id: user.id,
        hospital_id: hospitalId,
        booking_number: '', // Will be auto-generated by trigger
        customer_name: user.user_metadata?.full_name || 'Unknown',
        customer_email: user.email || '',
        customer_phone: user.user_metadata?.phone || '',
        start_date: startDate,
        end_date: endDate,
        price_paid: totalPrice,
        package_name: packageName,
        package_type: packageType,
        duration_months: Math.ceil(durationDays / 30), // Convert days to months
        special_requests: specialRequests || notes,
        payment_status: 'pending',
        status: 'pending',
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Error creating hospital appointment:', bookingError);
      return NextResponse.json(
        { error: 'Failed to create hospital appointment' },
        { status: 500 }
      );
    }

    // Send appointment confirmation email
    try {
      // Fetch hospital details for email
      const { data: hospital } = await supabase
        .from('hospitals')
        .select('hospital_name, hospital_name_english, slug')
        .eq('id', hospitalId)
        .single();

      if (hospital && appointment) {
        await sendBookingConfirmationEmail({
          to: appointment.customer_email || user.email || '',
          customerName: appointment.customer_name || 'คุณลูกค้า',
          bookingNumber: appointment.booking_number || '',
          hospitalName: hospital.hospital_name || hospital.hospital_name_english || 'โรงพยาบาล',
          packageName: appointment.package_name || packageName,
          packageType: (appointment.package_type as 'one_time' | 'package') || packageType as 'one_time' | 'package',
          startDate: appointment.start_date,
          endDate: appointment.end_date,
          pricePaid: appointment.price_paid || totalPrice,
          customerPhone: appointment.customer_phone,
          specialRequests: appointment.special_requests || specialRequests,
          bookingUrl: hospital.slug ? `/dashboard/appointments` : undefined,
        });

        // Create in-app notification
        await supabase
          .from('notifications')
          .insert({
            user_id: user.id,
            type: 'booking_confirmation',
            title: 'ยืนยันการจองสำเร็จ',
            message: `การจองของคุณ ${appointment.booking_number || 'ใหม่'} ได้รับการยืนยันแล้ว`,
            link_url: '/dashboard/appointments',
            metadata: {
              booking_id: appointment.id,
              booking_number: appointment.booking_number,
            },
          });
      }
    } catch (emailError) {
      // Don't fail the appointment if email fails
      console.warn('Email notification error (appointment still successful):', emailError);
    }

    // Create affiliate conversion if user was referred
    try {
      const affiliateUserId = await getAffiliateUserIdForReferredUser(user.id);
      
      if (affiliateUserId && appointment) {
        // Create conversion directly in database (server-side)
        const { getCommissionRate, calculateCommissionAmount } = await import('@shared/lib/constants/affiliate');
        const commissionRate = await getCommissionRate('appointment');
        const commissionAmount = calculateCommissionAmount(totalPrice, commissionRate);

        // Check if conversion already exists (prevent duplicates)
        const { data: existingConversion } = await supabase
          .from('affiliate_conversions')
          .select('id')
          .eq('affiliate_user_id', affiliateUserId)
          .eq('referred_user_id', user.id)
          .eq('conversion_type', 'appointment')
          .eq('reference_id', appointment.id)
          .eq('reference_type', 'appointment')
          .maybeSingle();

        if (!existingConversion) {
          const { error: conversionError } = await supabase
            .from('affiliate_conversions')
            .insert({
              affiliate_user_id: affiliateUserId,
              referred_user_id: user.id,
              conversion_type: 'appointment',
              conversion_value: totalPrice,
              commission_rate: commissionRate,
              commission_amount: commissionAmount,
              status: 'pending', // Will be updated to 'confirmed' when payment succeeds
              reference_id: appointment.id,
              reference_type: 'appointment',
              referral_source: 'direct',
              metadata: {
                hospital_id: hospitalId,
                package_type: packageType,
                package_name: packageName,
                booking_number: appointment.booking_number,
              },
            });

          if (conversionError) {
            console.warn('Failed to create affiliate conversion:', conversionError);
          }
        }
      }
    } catch (affiliateError) {
      // Don't fail the appointment if affiliate conversion fails
      console.warn('Affiliate conversion error (appointment still successful):', affiliateError);
    }

    // Award gamification points for appointment
    try {
      // Check if this is user's first appointment
      const { data: existingBookings } = await supabase
        .from('appointments')
        .select('id')
        .eq('user_id', user.id)
        .limit(1);

      const isFirstBooking = !existingBookings || existingBookings.length === 0;

      // Award points based on appointment type and duration
      let pointsToAward = isFirstBooking ? 100 : 50;
      
      // Bonus points for long-term packages
      if (packageType === 'package' && durationDays >= 180) {
        pointsToAward += 75; // Long-term package bonus
      }

      await awardPoints({
        user_id: user.id,
        points: pointsToAward,
        action_type: 'appointment',
        action_description: isFirstBooking ? 'จองโรงพยาบาลครั้งแรก' : 
                           packageType === 'package' ? 'จองแพ็คเกจระยะยาว' : 'จองโรงพยาบาล',
        reference_id: appointment.id,
        reference_type: 'appointment',
      });

      // Update appointment streak
      await updateUserStreak({
        user_id: user.id,
        streak_type: 'appointment',
      });

    } catch (gamificationError) {
      // Don't fail the appointment if gamification fails
      console.warn('Gamification error (appointment still successful):', gamificationError);
    }

    return NextResponse.json(appointment);
  } catch (error) {
    console.error('Error in hospital appointment API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user's hospital appointments using helper function (recommended)
    const { data: appointments, error: bookingsError } = await supabase.rpc(
      'get_user_bookings',
      { user_id_param: user.id }
    );

    // Alternative: Direct query from appointments table
    // const { data: appointments, error: bookingsError } = await supabase
    //   .from('appointments')
    //   .select(
    //     `
    //     *,
    //     hospitals (
    //       id,
    //       hospital_name,
    //       hospital_name_english,
    //       location,
    //       slug,
    //       images
    //     ),
    //     orders (
    //       id,
    //       order_number,
    //       status,
    //       total_amount
    //     )
    //   `
    //   )
    //   .eq('user_id', user.id)
    //   .order('created_at', { ascending: false });

    if (bookingsError) {
      console.error('Error fetching hospital appointments:', bookingsError);
      return NextResponse.json(
        { error: 'Failed to fetch hospital appointments' },
        { status: 500 }
      );
    }

    return NextResponse.json(appointments);
  } catch (error) {
    console.error('Error in hospital appointments API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
