/**
 * Hardcoded Data
 * ข้อมูล hardcode สำหรับแสดงผลในแอพพลิเคชั่น
 */

import { hospital, Product, TreatmentPackage, Article } from "@shared/types";

// Medical Treatment Packages
export const PACKAGES: TreatmentPackage[] = [
  {
    id: 1,
    name: "ตรวจสุขภาพพื้นฐาน",
    duration_days: 1,
    base_price: 1500,
    description: "แพ็คเกจตรวจสุขภาพพื้นฐาน 1 วัน",
    inclusions: ["ตรวจสุขภาพทั่วไป", "ตรวจเลือดพื้นฐาน", "ปรึกษาแพทย์"],
  },
  {
    id: 2,
    name: "ตรวจสุขภาพครบวงจร",
    duration_days: 1,
    base_price: 5000,
    description: "แพ็คเกจตรวจสุขภาพครบวงจร",
    inclusions: [
      "ตรวจสุขภาพทั่วไป",
      "ตรวจเลือดครบวงจร",
      "X-Ray ปอด",
      "อัลตราซาวด์ช่องท้อง",
      "ปรึกษาแพทย์",
    ],
  },
  {
    id: 3,
    name: "แพ็คเกจตรวจสุขภาพรายปี",
    duration_days: 365,
    base_price: 12000,
    description: "แพ็คเกจตรวจสุขภาพรายปี พร้อมติดตามผล",
    inclusions: [
      "ตรวจสุขภาพครบวงจร",
      "รายงานผลละเอียด",
      "ปรึกษาแพทย์ 2 ครั้ง",
      "ติดตามผล 3 เดือน",
      "อาหารเสริมวิตามิน",
    ],
  },
];

// hospitals
export const hospitals: hospital[] = [
  {
    id: "1",
    slug: "lumpinee-medical-center",
    hospital_name: "โรงพยาบาลลุมพินี",
    hospital_name_english: "Lumpinee Medical Center",
    address: "6 Rama IV Road, Thung Maha Mek, Sathon, Bangkok 10120",
    hospital_details:
      "โรงพยาบาลลุมพินีเป็นโรงพยาบาลเอกชนชั้นนำที่มีชื่อเสียงในประเทศไทย ให้บริการทางการแพทย์ครบวงจรด้วยทีมแพทย์ผู้เชี่ยวชาญและเทคโนโลยีทางการแพทย์ที่ทันสมัย",
    socials: "facebook.com/lumpinee",
    hospital_type: "general",
    packages: [],
    services: ["ตรวจสุขภาพ", "ตรวจเลือด", "X-Ray", "อัลตราซาวด์", "ปรึกษาแพทย์"],
    phone: "02-123-4567",
    email: "info@lumpinee-medical.com",
    website: "https://www.lumpinee-medical.com",
  },
  {
    id: "2",
    slug: "fairtex-medical-center",
    hospital_name: "โรงพยาบาลแฟร์เท็กซ์",
    hospital_name_english: "Fairtex Medical Center",
    address: "221/12 Moo 1, Bang Pla, Bang Phli, Samut Prakan 10540",
    hospital_details:
      "โรงพยาบาลแฟร์เท็กซ์เป็นโรงพยาบาลเฉพาะทางที่มีชื่อเสียงระดับโลก ให้บริการทางการแพทย์ด้วยมาตรฐานสากลและทีมแพทย์ผู้เชี่ยวชาญ",
    socials: "facebook.com/fairtex",
    hospital_type: "specialized",
    packages: [],
    services: ["ตรวจสุขภาพ", "ตรวจเลือด", "X-Ray", "อัลตราซาวด์", "ตรวจหัวใจ"],
    phone: "02-234-5678",
    email: "info@fairtex-medical.com",
    website: "https://www.fairtex-medical.com",
  },
  {
    id: "3",
    slug: "tiger-medical",
    hospital_name: "โรงพยาบาลไทเกอร์",
    hospital_name_english: "Tiger Medical Hospital",
    address: "7/11 Moo 5, Soi Ta-iad, Chalong, Phuket 83130",
    hospital_details:
      "โรงพยาบาลไทเกอร์ตั้งอยู่ในจังหวัดภูเก็ต เป็นโรงพยาบาลขนาดใหญ่ที่มีชื่อเสียงระดับโลก ให้บริการทางการแพทย์ครบวงจรด้วยเทคโนโลยีที่ทันสมัย",
    socials: "facebook.com/tigermedical",
    hospital_type: "general",
    packages: PACKAGES,
    services: ["ตรวจสุขภาพ", "ตรวจเลือด", "X-Ray", "อัลตราซาวด์", "ตรวจตา", "ตรวจฟัน"],
    phone: "076-123-4567",
    email: "info@tiger-medical.com",
    website: "https://www.tiger-medical.com",
  },
  {
    id: "4",
    slug: "petchyindee-medical-center",
    hospital_name: "โรงพยาบาลเพชรยินดี",
    hospital_name_english: "Petchyindee Medical Center",
    address: "123 Rama IV Road, Bangkok 10110",
    hospital_details:
      "โรงพยาบาลเพชรยินดีเป็นโรงพยาบาลที่มีประวัติศาสตร์ยาวนาน ให้บริการทางการแพทย์ด้วยวิธีการรักษาแบบดั้งเดิมผสมผสานกับเทคโนโลยีสมัยใหม่",
    socials: "facebook.com/petchyindee",
    hospital_type: "clinic",
    packages: PACKAGES,
    services: ["ตรวจสุขภาพ", "ตรวจเลือด", "ปรึกษาแพทย์", "กายภาพบำบัด"],
    phone: "02-345-6789",
    email: "info@petchyindee-medical.com",
    website: "https://www.petchyindee-medical.com",
  },
];

// Products
export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "fairtex-medical-equipment-bgv1",
    nameThai: "อุปกรณ์การแพทย์แฟร์เท็กซ์ BGV1",
    nameEnglish: "Fairtex Medical Equipment BGV1",
    description:
      "Premium medical equipment. Perfect for treatment and patient care.",
    price: 2500,
    stock: 50,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 2,
    slug: "medical-protection-gear",
    nameThai: "อุปกรณ์ป้องกันทางการแพทย์",
    nameEnglish: "Medical Protection Gear",
    description:
      "High-quality medical protection equipment for patient care. Maximum safety.",
    price: 1800,
    stock: 30,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 3,
    slug: "medical-uniform-red",
    nameThai: "ชุดทางการแพทย์ สีแดง",
    nameEnglish: "Medical Uniform - Red",
    description: "Professional medical uniform. Comfortable and durable.",
    price: 800,
    stock: 100,
    category: "Apparel",
    image: undefined,
  },
  {
    id: 4,
    slug: "medical-bandage-roll",
    nameThai: "ผ้าพันแผล 180 นิ้ว",
    nameEnglish: "Medical Bandage Roll 180 inch",
    description: "Professional medical bandage. Essential for wound care.",
    price: 200,
    stock: 200,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 5,
    slug: "thai-herbal-liniment",
    nameThai: "น้ำมันนวดสมุนไพรไทย",
    nameEnglish: "Thai Herbal Liniment Oil",
    description: "Traditional Thai herbal oil for muscle relief and treatment.",
    price: 150,
    stock: 150,
    category: "Wellness",
    image: undefined,
  },
  {
    id: 6,
    slug: "therapy-equipment-120cm",
    nameThai: "อุปกรณ์กายภาพบำบัด 120 ซม.",
    nameEnglish: "Physical Therapy Equipment 120cm",
    description: "Professional therapy equipment for home or hospital treatment.",
    price: 5500,
    stock: 15,
    category: "Equipment",
    image: undefined,
  },
];

// Articles
export const ARTICLES: Article[] = [
  {
    id: "1",
    slug: "medical-history-traditions",
    title: "ประวัติศาสตร์การแพทย์ไทย: จากอดีตสู่ปัจจุบัน",
    excerpt: "เรียนรู้ประวัติศาสตร์การแพทย์ไทยที่ยาวนานหลายศตวรรษ ตั้งแต่การแพทย์แผนไทยดั้งเดิมจนถึงการแพทย์สมัยใหม่",
    content: "การแพทย์ไทยมีประวัติความเป็นมายาวนานหลายศตวรรษ เริ่มต้นจากการแพทย์แผนไทยดั้งเดิมที่ใช้สมุนไพรและวิธีการรักษาแบบโบราณ...",
    author: "ดร.สมชาย วิทยากร",
    date: "2025-01-15",
    category: "ประวัติศาสตร์",
    tags: ["การแพทย์", "ประวัติศาสตร์", "วัฒนธรรม"],
  },
  {
    id: "2",
    slug: "basic-medical-knowledge",
    title: "ความรู้พื้นฐานทางการแพทย์สำหรับผู้เริ่มต้น",
    excerpt: "คู่มือสำหรับผู้ที่สนใจเรียนรู้พื้นฐานทางการแพทย์ พร้อมความรู้ที่ควรรู้",
    content: "การเริ่มต้นเรียนรู้ทางการแพทย์อาจดูยาก แต่ด้วยพื้นฐานที่ถูกต้อง คุณจะสามารถเข้าใจระบบการทำงานของร่างกายได้อย่างรวดเร็ว...",
    author: "นพ.เทียน วิชาการ",
    date: "2025-01-10",
    category: "ความรู้",
    tags: ["ความรู้", "ผู้เริ่มต้น", "พื้นฐาน"],
  },
  {
    id: "3",
    slug: "medical-checkup-benefits",
    title: "5 ประโยชน์จากการตรวจสุขภาพที่คุณอาจไม่รู้",
    excerpt: "นอกจากการป้องกันโรค การตรวจสุขภาพยังมีประโยชน์มากมายต่อสุขภาพและคุณภาพชีวิต",
    content: "การตรวจสุขภาพเป็นประจำไม่ได้ช่วยแค่ป้องกันโรคเท่านั้น แต่ยังช่วยให้คุณรู้จักร่างกายของตัวเองและดูแลสุขภาพได้อย่างถูกต้อง...",
    author: "นพ.วิชัย สุขภาพดี",
    date: "2025-01-05",
    category: "สุขภาพ",
    tags: ["สุขภาพ", "ตรวจสุขภาพ", "ประโยชน์"],
  },
  {
    id: "4",
    slug: "famous-medical-doctors",
    title: "แพทย์ผู้เชี่ยวชาญในตำนาน 10 อันดับ",
    excerpt: "รู้จักกับแพทย์ผู้เชี่ยวชาญที่ยิ่งใหญ่ที่สุดในประวัติศาสตร์การแพทย์ไทย",
    content: "วงการแพทย์ไทยมีแพทย์ผู้เชี่ยวชาญที่ยิ่งใหญ่มากมายที่สร้างประวัติศาสตร์ให้กับวงการ...",
    author: "นักข่าวสุขภาพ สุรชัย",
    date: "2024-12-28",
    category: "บุคคล",
    tags: ["แพทย์", "ตำนาน", "ผู้เชี่ยวชาญ"],
  },
  {
    id: "5",
    slug: "medical-equipment-guide",
    title: "คู่มือเลือกซื้ออุปกรณ์การแพทย์สำหรับบ้าน",
    excerpt: "ไกด์สำหรับการเลือกซื้ออุปกรณ์การแพทย์พื้นฐานที่จำเป็นสำหรับบ้าน",
    content: "การเลือกอุปกรณ์การแพทย์ที่เหมาะสมสำหรับบ้านสำคัญมากสำหรับการดูแลสุขภาพเบื้องต้น...",
    author: "ผู้เชี่ยวชาญอุปกรณ์ สมศักดิ์",
    date: "2024-12-20",
    category: "อุปกรณ์",
    tags: ["อุปกรณ์", "บ้าน", "การซื้อ"],
  },
  {
    id: "6",
    slug: "medical-diet-nutrition",
    title: "โภชนาการเพื่อสุขภาพ: กินอย่างไรให้แข็งแรง",
    excerpt: "แนวทางการกินอาหารที่ถูกต้องสำหรับสุขภาพที่ดี",
    content: "โภชนาการที่ดีเป็นพื้นฐานสำคัญของสุขภาพที่ดีและชีวิตที่มีคุณภาพ...",
    author: "นักโภชนาการ ดร.สุดา",
    date: "2024-12-15",
    category: "โภชนาการ",
    tags: ["อาหาร", "โภชนาการ", "สุขภาพ"],
  },
  {
    id: "7",
    slug: "lumpinee-medical-center-renovation",
    title: "โรงพยาบาลลุมพินีเปิดใช้หลังการปรับปรุง - พร้อมต้อนรับผู้ป่วย",
    excerpt: "โรงพยาบาลลุมพินีเปิดให้บริการอีกครั้งหลังการปรับปรุงครั้งใหญ่ พร้อมระบบเทคโนโลยีทางการแพทย์ที่ทันสมัย",
    content: "โรงพยาบาลลุมพินีที่ได้รับการปรับปรุงครั้งใหญ่ได้เปิดให้บริการอีกครั้งแล้ว พร้อมด้วยเทคโนโลยีทางการแพทย์ที่ทันสมัยและสิ่งอำนวยความสะดวกที่ครบครัน...",
    author: "ผู้จัดการโรงพยาบาลลุมพินี",
    date: "2025-01-18",
    category: "ข่าวสาร",
    tags: ["ลุมพินี", "โรงพยาบาล", "การปรับปรุง"],
  },
  {
    id: "9",
    slug: "medical-conference-2025",
    title: "การประชุมทางการแพทย์ 2025 - แพทย์ไทยเตรียมความพร้อม",
    excerpt: "การประชุมทางการแพทย์นานาชาติปี 2025 จะจัดขึ้นในประเทศไทย แพทย์ไทยเตรียมความพร้อมอย่างเต็มที่",
    content: "การประชุมทางการแพทย์นานาชาติ 2025 เป็นการประชุมที่ยิ่งใหญ่ที่สุดของปี...",
    author: "สมาคมการแพทย์แห่งประเทศไทย",
    date: "2025-01-16",
    category: "ข่าวสาร",
    tags: ["การประชุม", "การแพทย์", "แพทย์ไทย"],
  },
  {
    id: "10",
    slug: "medical-technology-advancement",
    title: "ความก้าวหน้าทางเทคโนโลยีการแพทย์ - ความภาคภูมิใจของคนไทย",
    excerpt: "ประเทศไทยมีความก้าวหน้าทางเทคโนโลยีการแพทย์อย่างมาก นับเป็นความภาคภูมิใจของคนไทยทั้งชาติ",
    content: "ความก้าวหน้าทางเทคโนโลยีการแพทย์ในประเทศไทยถือเป็นความสำเร็จที่ยิ่งใหญ่...",
    author: "กระทรวงสาธารณสุข",
    date: "2025-01-14",
    category: "ข่าวสาร",
    tags: ["เทคโนโลยี", "การแพทย์", "ความก้าวหน้า"],
    isNew: true,
  },
  {
    id: "11",
    slug: "medical-tourism-phuket",
    title: "การท่องเที่ยวเชิงการแพทย์ที่ภูเก็ต - ดึงดูดนักท่องเที่ยวจากทั่วโลก",
    excerpt: "ภูเก็ตกลายเป็นจุดหมายปลายทางยอดนิยมสำหรับการท่องเที่ยวเชิงการแพทย์",
    content: "ภูเก็ตได้กลายเป็นศูนย์กลางการท่องเที่ยวเชิงการแพทย์ที่สำคัญของโลก...",
    author: "การท่องเที่ยวแห่งประเทศไทย",
    date: "2025-01-12",
    category: "ข่าวสาร",
    tags: ["ภูเก็ต", "การท่องเที่ยว", "การแพทย์"],
  },
  {
    id: "12",
    slug: "medical-education-curriculum",
    title: "การแพทย์เข้าสู่หลักสูตรการศึกษา - ส่งเสริมความรู้ด้านสุขภาพในโรงเรียน",
    excerpt: "กระทรวงศึกษาธิการประกาศบรรจุความรู้ด้านสุขภาพและการแพทย์เป็นวิชาเลือกในหลักสูตรการศึกษาขั้นพื้นฐาน",
    content: "การบรรจุความรู้ด้านสุขภาพและการแพทย์เป็นวิชาเลือกในหลักสูตรการศึกษาจะช่วยส่งเสริมความรู้ด้านสุขภาพให้กับเยาวชน...",
    author: "กระทรวงศึกษาธิการ",
    date: "2025-01-10",
    category: "ข่าวสาร",
    tags: ["การศึกษา", "หลักสูตร", "สุขภาพ"],
  },
];

